services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512m
    container_name: projetTI-backend
    ports:
      - "8080:80"
    environment:
      APP_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: watch_store
      DB_USER: watch_user
      DB_PASSWORD: watch_password
      CORS_ALLOWED_ORIGINS: http://localhost:5173
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin123
      ADMIN_API_KEY: change-me-api-key
    volumes:
      - ./apps/backend:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/docker-php-config.ini
    depends_on:
      - db

  db:
    image: mysql:9.5
    deploy:
      resources:
        limits:
          memory: 512m
    container_name: projetTI-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: watch_store
      MYSQL_USER: watch_user
      MYSQL_PASSWORD: watch_password
    volumes:
      - db_data:/var/lib/mysql
      - ./apps/backend/database/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    deploy:
      resources:
        limits:
          memory: 512m
    container_name: projetTI-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpass
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db

volumes:
  db_data:
