services:
  backend:
    hostname: localhost
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512m
    container_name: projetTI-backend
    restart: always
    environment:
      APP_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: belle_montre_wallone
      DB_USER: watch_user
      DB_PASSWORD: watch_password
      CORS_ALLOWED_ORIGINS: http://localhost:5173
      ADMIN_USER: root
      ADMIN_PASSWORD: change_me_admin_password
      ADMIN_API_KEY: change-me-api-key
      JWT_SECRET: super-secret-jwt
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/docker-php-config.ini
    depends_on:
      - db

  db:
    image: mysql:9.5
    deploy:
      resources:
        limits:
          memory: 512m
    container_name: projetTI-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: belle_montre_wallone
      MYSQL_USER: watch_user
      MYSQL_PASSWORD: watch_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database/DBTable.sql:/docker-entrypoint-initdb.d/01.sql
      - ./database/DBInsert.sql:/docker-entrypoint-initdb.d/02.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    deploy:
      resources:
        limits:
          memory: 512m
    container_name: projetTI-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    depends_on:
      - db
    ports:
      - "8081:80"

volumes:
  db_data:
